export const CATEGORIES_ACTION_TYPES = {
    UPDATE_ADD_PRODUCT_START: 'UPDATE_ADD_PRODUCT_START',
    UPDATE_ADD_PRODUCT_SUCCESS: 'UPDATE_ADD_PRODUCT_SUCCESS',
    UPDATE_ADD_PRODUCT_FAILED: 'UPDATE_ADD_PRODUCT_FAILED',
    UPDATE_ID: 'UPDATE_ID'
}