export const CART_ACTION_TYPES = {
    OPT_SELECT_IS_CART_OPEN: 'OPT_SELECT_IS_CART_OPEN',
    UPDATE_SET_CART_ITEMS: 'UPDATE_SET_CART_ITEMS',
    UPDATE_ON_CHECHOUT_START: 'UPDATE_ON_CHECHOUT_START',
    UPDATE_ON_CHECHOUT_SUCCESS: 'UPDATE_ON_CHECHOUT_SUCCESS',
    UPDATE_ON_CHECHOUT_FAILED: 'UPDATE_ON_CHECHOUT_FAILED',
}