export const CATEGORIES_ACTION_TYPES = {
    ADD_PRODUCT_START: 'categories/ADD_PRODUCT_START',
    ADD_PRODUCT_SUCCESS: 'categories/ADD_PRODUCT_SUCCESS',
    ADD_PRODUCT_FAILED: 'categories/ADD_PRODUCT_FAILED',
}