export const CART_ACTION_TYPES = {
    SELECT_IS_CART_OPEN: 'cart/SELECT_IS_CART_OPEN',
    SET_CART_ITEMS: 'cart/SET_CART_ITEMS',
    ON_CHECHOUT_START: 'cart/ON_CHECHOUT_START',
    ON_CHECHOUT_SUCCESS: 'cart/ON_CHECHOUT_SUCCESS',
    ON_CHECHOUT_FAILED: 'cart/ON_CHECHOUT_FAILED',
}